### ISSUE TITLE
Sonorous demo on codpen - Mute All button doesn't work on Firefox

### ISSUE THREAD

**Issue by knowledgeReignsSupreme** [EkoLabs/sonorous#23]
**Please fill out this report when filing a bug. Without this report, there may be delays in addressing your bug.**

**Describe the bug**
Hello. While trying the Sonorous demo as it's posted on https://eko.engineering/sonorous/  - it appears that the Mute All button doesn't function at all on Mozilla Firefox.

**Have you followed the required steps before opening a bug report?**
(Check the step you've followed - put an `x` character between the square brackets `[]`)
* [x] I have reviewed [the documentation](https://github.com/EkoLabs/sonorous/blob/master/README.md) in its entirety, included the dedicated documentations.
* [x] I have searched for [existing issues](https://github.com/EkoLabs/sonorous/issues) and made sure that the problem hasn't already been reported.
* [x] I am using [the latest version](https://github.com/EkoLabs/sonorous/releases).

**Expected behavior**
The Mute All button should mute Sonorous entirely

**Actual behavior**
The Mute All button doesn't function at all. It does nothing.
FYI: All other mute buttons are working just fine.

**Browser (please complete the following information):**
 Mozilla Firefox 88.0.1

**To Reproduce**
1. Open Mozilla Firefox
2. Go to https://eko.engineering/sonorous/
3. Play the demo track
4. Click the Mute All button

**Screenshots**
Not applicable.

**Additional context**
Tested also using Opera version 76.0 and Chromium version 99.0 - it's working as expected on those browsers.

Edit: I also tested this functionality on my local environment by cloning this repo and the Mute All button works just fine. Seems like an issue with the code on CodePen.
link: https://codepen.io/OpherV/pen/PoPQwaz

btw the guitar rocks on the demo track!

Thanks

**Comment by OpherV** [comment]
@knowledgeReignsSupreme thanks for reporting!

@DivyaMahadevan I can repro. Maybe something to do with iFrame security permissions and the master audio context? Sonor-specific mutes work fine

**Comment by DivyaMahadevan** [comment]
@knowledgeReignsSupreme Thanks for bringing this to our attention! The issue should be resolved now (you may need to clear cache).
